---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-test
  namespace: kube-system
  labels:
    app: k8s-sidecar-injector
    track: test
data:
  filebrowser: |
    name: filebrowser
    containers:
    - name: sidecar-filebrowser
      image: registry.cn-beijing.aliyuncs.com/greyballoon/filebrowser:latest  #filebrowser/filebrowser
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 80
    volumes:
    - name: whole-volume
      emptyDir: {}
    volumeMounts:
    - mountPath: /wholeshare
      name: whole-volume
    env:
    - name: HELLO
      value: "world"
    - name: HEY
      value: "hey"
  another: |
    name: another
    containers:
    - name: sidecar-another
      image: registry.cn-hangzhou.aliyuncs.com/google_containers/busybox
      imagePullPolicy: IfNotPresent
      command: ['sh', '-c', 'echo The app is running! && sleep 3600']
      volumeMounts:
      - mountPath: /anotherwhole
        name: whole-volume2
    - name: sidecar-another
      image: registry.cn-hangzhou.aliyuncs.com/google_containers/busybox
      imagePullPolicy: IfNotPresent
    volumes:
    - name: whole-volume
      emptyDir: {}
    - name: whole-volume2
      emptyDir: {}
    volumeMounts:
    - mountPath: /wholeshare
      name: whole-volume
    env:
    - name: HELLO
      value: "world"
    - name: HEY2
      value: "hey2"
