---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-test
  namespace: kube-system
  labels:
    app: k8s-sidecar-injector
    track: test
data:
  filebrowser: |
    name: filebrowser
    containers:
    - name: sidecar-filebrowser
      image: registry.cn-beijing.aliyuncs.com/greyballoon/filebrowser:latest  #filebrowser/filebrowser
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 80
    volumes:
    - name: whole-volume
      emptyDir: {}
    volumeMounts:
    - mountPath: /wholeshare
      name: whole-volume  
