apiVersion: v1
kind: Pod
metadata:
  name: debugpod2
  namespace: default
  labels:
    app: myApp2
  annotations:
    injector.tumblr.com/request: filebrowser
spec:
  containers:
  - name: myapp-busybox
    image: registry.cn-hangzhou.aliyuncs.com/google_containers/busybox
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
